### ISSUE TITLE
Internal 4K monitor not working

### ISSUE THREAD

**Issue by retomi** [Cluas/Dell-7570-Hackintosh#1]
Hello
I have the model with 4k monitor and it works everything apart from the monitor. It's always black and I'm forced to use a hdmi monitor. Can you help me about it? Thanks so much

**Comment by Cluas** [comment]
Did you run all the steps in my tutorial?

**Comment by Cluas** [comment]
@retomi Did you run all the steps in my tutorial?
using [this](https://github.com/Cluas/Dell-7570-Hackintosh/tree/master/%E4%B8%80%E9%94%AE%E5%BC%80%E5%90%AFHIDPI%E5%B9%B6%E6%B3%A8%E5%85%A5EDID)

**Comment by retomi** [comment]
Yes, i run all steps. This is what I did:
1. I create a bootable usb like this: sudo / Applications / Install \ macOS \ High \ Sierra.app/Contents/Resources/createinstallmedia --volume / Volumes / MY_USB - applicationpath / Applications / Install \ macOS \ High \ Sierra. app --nointeraction
2. I install Clover EFI on the newly created usb drive
2.1 select "Install for UEFI booting only"
2.2 select "Install Clover in the ESP"
3. I replace the contents of the USB EFI / Clover folder with your Clover folder
4. boot the laptop with the USB flash drive
5. after boot is over the monitor is black and I have to connect a hdmi monitor to complete the installation
6. complete the installation I install EFI Clover on SSD
7. I replace the contents of the EFI / Clover folder of the SSD with your Clover folder
8. I run install 双击 自动 安装 .command
9. I execute 双击 .command
10. reboot
unfortunately, however, the internal monitor is always black and I can only use an external monitor
Is the procedure described correct?

Thank you very much

**Comment by Cluas** [comment]
@retomi I installed two DELL notebooks

It's all right.
It would be best if you could provide the error log in the boot time.

**Comment by dmatora** [comment]
@Cluas did you install it on 4K display model?

**Comment by Cluas** [comment]
@dmatora I install it on 2k display model, but in theory, it can support 4K documents according to plugins.

**Comment by dmatora** [comment]
@Cluas so far, everyone who tried it on 4K monitor got black screen

**Comment by Cluas** [comment]
@dmatora Have you tried installing this plugin? [https://github.com/Cluas/Dell-7570-Hackintosh/tree/master/%E4%B8%80%E9%94%AE%E5%BC%80%E5%90%AFHIDPI%E5%B9%B6%E6%B3%A8%E5%85%A5EDID]

**Comment by dmatora** [comment]
I don't have it, thinking about making purchase, but without working 4K monitor I'd rather buy something else

**Comment by Cluas** [comment]
@dmatora This plugin supports 4k resolution.

**Comment by Cluas** [comment]
@dmatora You can find a friend with a 4k monitor to test it.

**Comment by dmatora** [comment]
@Cluas I have monitor, I don't have a laptop :)

**Comment by Cluas** [comment]
@dmatora Haha, I don't have this notebook now too, or I can test it for you.

**Comment by dmatora** [comment]
@Cluas peluzitol says he tried this repo ( https://www.tonymacx86.com/threads/problem-with-internal-laptop-lcd-in-hackintosh-dell-7570.259910/ ) with no success

**Comment by Cluas** [comment]
@dmatora I used to display perfectly on the 2k display.

**Comment by dmatora** [comment]
@Cluas doesn't really prove anything :)
for example 2K works via HDMI 1.4, 4K@60Hz doesn't

**Comment by Cluas** [comment]
@dmatora I am sorry I can't help you.
