### ISSUE TITLE
NOT WORK with  Mojave 10.14

### ISSUE THREAD

**Issue by vanthao03596** [Cluas/Dell-7570-Hackintosh#3]
I tried your clover with  Mojave 10.14 but my laptop stuck in first time boot.

**Comment by Cluas** [comment]
@vanthao03596 sorry . this clover is for 10.13.

**Comment by vanthao03596** [comment]
> @vanthao03596 sorry . this clover is for 10.13.

I installed successful but i get error with my sound. Can u guide me to fix this ?

**Comment by Cluas** [comment]
@vanthao03596 sorry .. I don't know how to fix it in 10.14. maybe you can downgrade to10.13

**Comment by vanthao03596** [comment]
Do u have plan for 10.14 ?

**Comment by Cluas** [comment]
@vanthao03596 I am so sorry, this is done using the company's computer. I don't have a computer of this model right now.
